image: "edge_test/build_test:latest"
build_args:
  ROOT_PASS: password
  ANSIBLE_VER: 
  RUBY_VER: 2.3.0
  ITAMAE_VER: 
  SERVERSPEC_VER: 
  INFRATASTER_VER: 
  DOCKER_API_VER: 
  DOCKER_COMPOSE_VER: 1.11.2
